name: Release Single Image
on:
  workflow_dispatch:
    inputs:
      pipeline-argument:
        description: 'Argument to pass to pipeline'
        required: true
      image-tag:
        description: 'Image tag to build'
        required: true
jobs:
  release-single-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          #/usr/bin/git config --global --add safe.directory /home/runner/work/test-build-mongodb-operator/test-build-mongodb-operator/test-build-mongodb-operator
          path: test-build-mongodb-operator

      - name: Checkout mongodb operator
        uses: actions/checkout@v4
        with:
          repository: "mongodb/mongodb-kubernetes-operator"
          ref: 'v0.10.0'
          #/usr/bin/git config --global --add safe.directory /home/runner/work/test-build-mongodb-operator/test-build-mongodb-operator/mongodb-kubernetes-operator
          path: mongodb-kubernetes-operator

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
          architecture: 'x64'

#      - name: Debug directories with working-directory
#        working-directory: /home/runner/work/test-build-mongodb-operator/test-build-mongodb-operator
#        run: |
#          ls -alh ./
#          pwd
#          ls -alh ./test-build-mongodb-operator
#          ls -alh ./mongodb-kubernetes-operator
#
#      - name: Debug directories
#        run: |
#          ls -alh ./
#          pwd
#          ls -alh ./test-build-mongodb-operator
#          ls -alh ./mongodb-kubernetes-operator

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('./mongodb-kubernetes-operator/requirements.txt') }}

      - name: Install Python Dependencies
        run: pip install -r ./mongodb-kubernetes-operator/requirements.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # template: .action_templates/steps/set-up-qemu.yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Override some files of mongodb operator
        run: |
          cp ./test-build-mongodb-operator/mongodb/config.json ./mongodb-kubernetes-operator/scripts/ci/config.json
          cp ./test-build-mongodb-operator/mongodb/operator-inventory.yaml ./mongodb-kubernetes-operator/inventories/operator-inventory.yaml
          cp ./test-build-mongodb-operator/mongodb/pipeline.py ./mongodb-kubernetes-operator/pipeline.py
          cp ./test-build-mongodb-operator/mongodb/Dockerfile.ubi ./mongodb-kubernetes-operator/scripts/dev/templates/agent/Dockerfile.ubi

      - name: Build and Push Image To ghcr.io
        working-directory: ./mongodb-kubernetes-operator
        run: python pipeline.py --image-name ${{ github.event.inputs.pipeline-argument }} --tag ${{ github.event.inputs.image-tag }}
        env:
          MONGODB_COMMUNITY_CONFIG: "${{ github.workspace }}/mongodb-kubernetes-operator/scripts/ci/config.json"
          version_id: "${{ github.event.inputs.image-tag }}"

